# Generated by Django 5.0.6 on 2026-06-03 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise_nom', models.CharField(default='Eden Agro Business', max_length=255)),
                ('entreprise_adresse', models.TextField(default='Conakry - Guinée')),
                ('entreprise_telephone', models.CharField(default='+224 XXX XX XX XX', max_length=30)),
                ('entreprise_email', models.EmailField(default='contact@edenagro.com', max_length=254)),
                ('entreprise_site', models.URLField(blank=True, null=True)),
                ('entreprise_logo', models.ImageField(blank=True, null=True, upload_to='entreprise/logo/')),
                ('entreprise_rccm', models.CharField(blank=True, max_length=100, null=True)),
                ('entreprise_nif', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=50, unique=True)),
                ('client_nom', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('produit', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('valide_par_dg', models.BooleanField(default=False)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée DG'), ('payee', 'Payée')], default='en_attente', max_length=20)),
                ('commentaire_validation', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
