# Generated by Django 5.0.6 on 2026-06-03 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.TextField()),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmée', 'Confirmée'), ('Préparation', 'Préparation'), ('Livrée', 'Livrée'), ('Annulée', 'Annulée')], default='En attente', max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
            ],
        ),
    ]
