# Generated by Django 6.0.5 on 2026-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_media_delete_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('gallery', 'Galerie'), ('blog', 'Blog')], default='gallery', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
    ]
