# Generated by Django 6.0.5 on 2026-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='google_maps',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='Conakry, Guinée', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
