# Generated by Django 5.0.6 on 2026-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('code_suivi', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('chauffeur', models.CharField(max_length=255)),
                ('produit', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('expediee', 'Expédiée'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
