# Generated by Django 6.0.5 on 2026-05-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('presentation', models.TextField()),
                ('history', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('team', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
