# Generated by Django 5.0.6 on 2026-06-04 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panier', '0002_panier_user_alter_panier_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panieritem',
            name='created_at',
        ),
    ]
