# Generated by Django 5.0.6 on 2026-05-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ecommerce', to='produits.produit')),
            ],
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stocks.stock')),
            ],
        ),
    ]
